services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - ./db/seed/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


  dbdocs:
    container_name: dbdocs
    image: node:20
    tty: true
    command: >
      npm install -g dbdocs && \
      npm list -g